### ISSUE TITLE
macOS rpath to shared libraries not being set correctly

### ISSUE THREAD

**Issue by omarfsosa** [stan-dev/pystan-next#128]
#### Summary

Any attempt at building a model quickly raises a `ContentTypeError: 0`. 

#### Description

Here is the error I get with a full stack trace:
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/Users/omarfsosa/anaconda3/envs/pystan3/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/omarfsosa/anaconda3/envs/pystan3/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/Users/omarfsosa/anaconda3/envs/pystan3/lib/python3.7/site-packages/httpstan/views.py", line 92, in handle_models
    httpstan.models.import_services_extension_module(model_name)
  File "/Users/omarfsosa/anaconda3/envs/pystan3/lib/python3.7/site-packages/httpstan/models.py", line 92, in import_services_extension_module
    module: ModuleType = importlib.util.module_from_spec(spec)  # type: ignore
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/omarfsosa/Library/Caches/httpstan/2.0.2/models/og6op66v/services_og6op66v.cpython-37m-darwin.so, 2): Library not loaded: /Users/travis/build/stan-dev/httpstan-wheels/httpstan/httpstan/lib/libprotobuf-lite.22.dylib
  Referenced from: /Users/omarfsosa/Library/Caches/httpstan/2.0.2/models/og6op66v/services_og6op66v.cpython-37m-darwin.so
  Reason: image not found
---------------------------------------------------------------------------
ContentTypeError                          Traceback (most recent call last)
<ipython-input-3-e758df3e7b5c> in <module>
----> 1 sm = stan.build(code, random_seed=1)

~/anaconda3/envs/pystan3/lib/python3.7/site-packages/stan/model.py in build(program_code, data, random_seed)
    228             return Model(model_name, program_code, data, param_names, constrained_param_names, dims, random_seed)
    229
--> 230     return asyncio.run(go())

~/anaconda3/envs/pystan3/lib/python3.7/asyncio/runners.py in run(main, debug)
     41         events.set_event_loop(loop)
     42         loop.set_debug(debug)
---> 43         return loop.run_until_complete(main)
     44     finally:
     45         try:

~/anaconda3/envs/pystan3/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    585             raise RuntimeError('Event loop stopped before Future completed.')
    586
--> 587         return future.result()
    588
    589     def stop(self):

~/anaconda3/envs/pystan3/lib/python3.7/site-packages/stan/model.py in go()
    214                 # print('resp statuts:', resp.status)
    215                 if resp.status != 201:
--> 216                     raise RuntimeError((await resp.json())["message"])
    217                 model_name = (await resp.json())["name"]
    218

~/anaconda3/envs/pystan3/lib/python3.7/site-packages/aiohttp/client_reqrep.py in json(self, encoding, loads, content_type)
   1029                     message=('Attempt to decode JSON with '
   1030                              'unexpected mimetype: %s' % ctype),
-> 1031                     headers=self.headers)
   1032
   1033         stripped = self._body.strip()  # type: ignore

ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:53366/v1/models')
```

I imagine the relevant part is that I'm missing this: `/Users/travis/build/stan-dev/httpstan-wheels/httpstan/httpstan/lib/libprotobuf-lite.22.dylib`, but to be honest I have no clue.

#### Reproducible steps:
From an python session:
```
import stan
code = """parameters {real y;} model {y ~ normal(0, 1);}"""
sm = stan.build(code)
```

### Pystan version: 
3.0.0-beta.1

### OS:
MacOS Catalina, 10.15.5

**Comment by riddell-stan** [comment]
Thanks for the report. This is an interesting error. You should certainly receive a more informative error.

We do test on macOS but not with anaconda. Any chance you could confirm this happens with normal (non-anaconda) Python 3.7?

**Comment by riddell-stan** [comment]
Actually, I think I see the problem. The rpath is not updated. It's looking for the `libprotobuf-lite.22.dylib` in the travis directory (where we build the wheel): `/Users/travis/build/stan-dev/httpstan-wheels/httpstan/httpstan/lib/`.

**Comment by riddell-stan** [comment]
I hope this isn't anaconda fiddling with the rpath. See <https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#detect-binary-files-with-prefix>.

If someone can confirm this bug on macOS (without anaconda) we should pull the macOS release so macOS users don't install a broken piece of software.

**Comment by ahartikainen** [comment]
I think we could try this with CI (e.g. gh actions) with some special repo just to test install + compilation.

**Comment by riddell-stan** [comment]
I'm looking into getting access to a macOS machine. Might take some time.

**Comment by riddell-stan** [comment]
Confirmed on official CPython. I'll delete the macos httpstan wheel.

**Comment by riddell-stan** [comment]
@omarfsosa This is now fixed on macOS. You may need to uninstall/reinstall/upgrade.

**Comment by omarfsosa** [comment]
> @omarfsosa This is now fixed on macOS. You may need to uninstall/reinstall/upgrade.

Thank you for the quick fix! It's working now :)
