### ISSUE TITLE
Bug: JSON output missing from response

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#135]
Hi, apparently some return codes fail to return JSON?

I'm trying to run the following model

```
import stan
model_code = """
functions {
  real partial_sum(int[] slice_n_redcards,
                   int start, int end,
                   int[] n_games,
                   vector rating,
                   vector beta) {
    return binomial_logit_lpmf(slice_n_redcards |
                               n_games[start:end],
                               beta[1] + beta[2] * rating[start:end]);
  }
}
data {
  int<lower=0> N;
  int<lower=0> n_redcards[N];
  int<lower=0> n_games[N];
  vector[N] rating;
  int<lower=1> grainsize;
}
parameters {
  vector[2] beta;
}
model {

  beta[1] ~ normal(0, 10);
  beta[2] ~ normal(0, 1);

  target += reduce_sum(partial_sum, n_redcards, grainsize,
                       n_games, rating, beta);
}
"""
import pandas as pd
data = pd.read_csv("./RedcardData.csv")
data = data.dropna(subset=["rater1"])

stan_data = {
    "N" : data.shape[0],
    "n_redcards" : data["redCards"].values,
    "n_games" : data["games"].values,
    "rating" : data["rater1"].values,
    "grainsize" : 1,
}

posterior = stan.build(model_code, data=stan_data)

import os
os.environ["STAN_NUM_THREADS"] = "4"

fit = posterior.sample(num_chains=1, num_samples=1000)
```

And at the `posterior = stan.build` step causes exception

```
Traceback (most recent call last):
  File "example_model.py", line 46, in <module>
    posterior = stan.build(model_code, data=stan_data)
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/stan/model.py", line 241, in build
    return asyncio.run(go())
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/stan/model.py", line 233, in go
    raise RuntimeError((await resp.json())["message"])
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:50261/v1/models/idrrhyot/params')
```

Printing resp gives:

```
<ClientResponse(http://127.0.0.1:50384/v1/models/idrrhyot/params) [413 Request Entity Too Large]>
<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '68', 'Date': 'Fri, 31 Jul 2020 08:51:29 GMT', 'Server': 'Python/3.8 aiohttp/3.6.2')>
```

Adding `content_type='text/plain; charset=utf-8'` or `content_type=None` to `resp.json` call causes

```
Traceback (most recent call last):
  File "example_model.py", line 46, in <module>
    posterior = stan.build(model_code, data=stan_data)
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/stan/model.py", line 241, in build
    return asyncio.run(go())
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/stan/model.py", line 233, in go
    raise RuntimeError((await resp.json(content_type='text/plain; charset=utf-8'))["message"])
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ahartikainen/miniconda3/envs/stan/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Which would mean that the json is missing?

Printing `resp.__dict__` gives

```
{'method': 'POST', 'cookies': <SimpleCookie: >, '_real_url': URL('http://127.0.0.1:50531/v1/models/idrrhyot/params'), '_url': URL('http://127.0.0.1:50531/v1/models/idrrhyot/params'), '_body': None, '_writer': None, '_continue': None, '_closed': True, '_history': (), '_request_info': RequestInfo(url=URL('http://127.0.0.1:50531/v1/models/idrrhyot/params'), method='POST', headers=<CIMultiDictProxy('Host': '127.0.0.1:50531', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Content-Length': '1431557', 'Content-Type': 'application/json')>, real_url=URL('http://127.0.0.1:50531/v1/models/idrrhyot/params')), '_timer': <aiohttp.helpers.TimerContext object at 0x7ff312fd64c0>, '_cache': {'headers': <CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '68', 'Date': 'Fri, 31 Jul 2020 08:57:48 GMT', 'Server': 'Python/3.8 aiohttp/3.6.2')>, 'url': URL('http://127.0.0.1:50531/v1/models/idrrhyot/params')}, '_traces': [], '_loop': <_UnixSelectorEventLoop running=True closed=False debug=False>, '_session': None, '_protocol': <aiohttp.client_proto.ResponseHandler object at 0x7ff313d83880>, '_connection': None, 'version': HttpVersion(major=1, minor=1), 'status': 413, 'reason': 'Request Entity Too Large', '_headers': <CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '68', 'Date': 'Fri, 31 Jul 2020 08:57:48 GMT', 'Server': 'Python/3.8 aiohttp/3.6.2')>, '_raw_headers': ((b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'68'), (b'Date', b'Fri, 31 Jul 2020 08:57:48 GMT'), (b'Server', b'Python/3.8 aiohttp/3.6.2')), 'content': <StreamReader 68 bytes eof>}
```

So I think this is a `httpstan` error for  `'status': 413, 'reason': 'Request Entity Too Large'`?

httpstan version: '2.0.4' (pypi)
pystan version: '3.0.0-beta.1' (pypi)
OS: Ubuntu (WSL1)

**Comment by riddell-stan** [comment]
Closed in https://github.com/stan-dev/httpstan/pull/418
