### ISSUE TITLE
Cannot compile model using Pystan 3.0.0b4 ('/usr/bin/gcc' failed with exit code 1")

### ISSUE THREAD

**Issue by Auerilas** [stan-dev/pystan-next#168]
Hi all,
I cannot compile models using Pystan 3.0.0b4. (Note, on this same system, I have the latest version of PyStan - 2.19.1.1, and it works fine!)

Here's my code:

```
(base)$ conda create -n pystantest python=3.9 numpy cython pip
(base)$ conda activate pystantest

(pystantest)$ python3 -m pip install --pre pystan
Collecting pystan
  Using cached pystan-3.0.0b4-py3-none-any.whl (10 kB)
Collecting httpstan<3.0.0,>=2.3.0
  Using cached httpstan-2.3.0-cp39-cp39-manylinux2014_x86_64.whl (60.8 MB)
Collecting aiohttp<4.0,>=3.6
  Using cached aiohttp-3.7.2-cp39-cp39-manylinux2014_x86_64.whl (1.4 MB)
Collecting clikit<0.7.0,>=0.6.2
  Using cached clikit-0.6.2-py2.py3-none-any.whl (91 kB)
Requirement already satisfied: numpy<2.0,>=1.7 in ./miniconda3/envs/pystantest/lib/python3.9/site-packages (from pystan) (1.19.4)
Collecting marshmallow<4.0,>=3.2
  Using cached marshmallow-3.9.1-py2.py3-none-any.whl (46 kB)
Collecting protobuf<4.0,>=3.13
  Using cached protobuf-3.14.0rc1-py2.py3-none-any.whl (173 kB)
Collecting appdirs<2.0,>=1.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting webargs<7.0,>=6.1
  Using cached webargs-6.1.1-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: setuptools>=41.0 in ./miniconda3/envs/pystantest/lib/python3.9/site-packages (from httpstan<3.0.0,>=2.3.0->pystan) (49.6.0.post20201009)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.2-cp39-cp39-manylinux2014_x86_64.whl (320 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.0.0-cp39-cp39-manylinux2014_x86_64.whl (151 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting crashtest<0.4.0,>=0.3.0; python_version >= "3.6" and python_version < "4.0"
  Using cached crashtest-0.3.1-py3-none-any.whl (7.0 kB)
Collecting pastel<0.3.0,>=0.2.0
  Using cached pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
Collecting pylev<2.0,>=1.3
  Using cached pylev-1.3.0-py2.py3-none-any.whl (4.9 kB)
Collecting six>=1.9
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting idna>=2.0
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: marshmallow, async-timeout, idna, multidict, yarl, chardet, attrs, typing-extensions, aiohttp, six, protobuf, appdirs, webargs, httpstan, crashtest, pastel, pylev, clikit, pystan
Successfully installed aiohttp-3.7.2 appdirs-1.4.4 async-timeout-3.0.1 attrs-20.3.0 chardet-3.0.4 clikit-0.6.2 crashtest-0.3.1 httpstan-2.3.0 idna-2.10 marshmallow-3.9.1 multidict-5.0.0 pastel-0.2.1 protobuf-3.14.0rc1 pylev-1.3.0 pystan-3.0.0b4 six-1.15.0 typing-extensions-3.7.4.3 webargs-6.1.1 yarl-1.6.2



(pystantest)$ python
Python 3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:59:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import stan

schools_code = """
data {
  int<lower=0> J;         // number of schools
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"""

schools_data = {"J": 8,
                "y": [28,  8, -3,  7, -1,  1, 18, 12],
                "sigma": [15, 10, 16, 11,  9, 11, 10, 18]}


posterior = stan.build(schools_code, data=schools_data, random_seed=1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/site-packages/stan/model.py", line 302, in build
    return asyncio.run(go())
  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/site-packages/stan/model.py", line 286, in go
    raise RuntimeError(response_payload["message"])
RuntimeError: Exception while building model extension module: `CompileError(DistutilsExecError("command '/usr/bin/gcc' failed with exit code 1"))`, traceback: `['  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/site-packages/httpstan/views.py", line 113, in handle_create_model\n    compiler_output = await httpstan.models.build_services_extension_module(program_code)\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/site-packages/httpstan/models.py", line 177, in build_services_extension_module\n    compiler_output = await asyncio.get_event_loop().run_in_executor(\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/concurrent/futures/thread.py", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/site-packages/httpstan/build_ext.py", line 80, in run_build_ext\n    build_extension.run()\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/command/build_ext.py", line 340, in run\n    self.build_extensions()\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions\n    self._build_extensions_serial()\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial\n    self.build_extension(ext)\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension\n    objects = self.compiler.compile(sources,\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/ccompiler.py", line 574, in compile\n    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n', '  File "/home/nate/miniconda3/envs/pystantest/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile\n    raise CompileError(msg)\n']`
```
Thoughts?

**Comment by Auerilas** [comment]
NM, apparently I had to install the g++ compilers (because newer version of stan use g++ and not gcc, I guess?

sudo apt-get install g++

That solved it.
