### ISSUE TITLE
AssertionError with num_flat_params and constrained_param_names

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#56]
Hi,

I have a simple model which won't sample.

```
import stan as stan
import numpy as np

schools_code = """
data {
             int<lower=0> J;
             real y[J];
             real<lower=0> sigma[J];
}
parameters {
             real mu;
             real<lower=0> tau;
             real theta_tilde[J];
}
transformed parameters {
             real theta[J];
             for (j in 1:J)
                 theta[j] = mu + tau * theta_tilde[j];
}
model {
             mu ~ normal(0, 5);
             tau ~ cauchy(0, 5);
             theta_tilde ~ normal(0, 1);
             y ~ normal(theta, sigma);
}
generated quantities {
             vector[J] log_lik;
             vector[J] y_hat;
             for (j in 1:J) {
                 log_lik[j] = normal_lpdf(y[j] | theta[j], sigma[j]);
                 y_hat[j] = normal_rng(theta[j], sigma[j]);
             }
}
"""

data = {
    "J": 8,
    "y": np.array([28.0, 8.0, -3.0, 7.0, -1.0, 1.0, 18.0, 12.0]),
    "sigma": np.array([15.0, 10.0, 16.0, 11.0, 9.0, 11.0, 10.0, 18.0]),
}

posterior = stan.build(schools_code, data=data)
fit = posterior.sample(num_chains=4, num_samples=100, num_warmup=0)
```

This will give the following exception

```
Traceback (most recent call last):
  File "run_sc.py", line 43, in <module>
    fit = stan_model.sample(num_chains=4, num_samples=100, num_warmup=0)
  File ".../miniconda3/envs/stan3/lib/python3.7/site-packages/stan/model.py", line 176, in sample
    save_warmup,
  File ".../miniconda3/envs/stan3/lib/python3.7/site-packages/stan/fit.py", line 58, in __init__
    assert num_flat_params == len(constrained_param_names)
AssertionError
```

This compiles and samples fine with PyStan 2.18.

**Comment by ahartikainen** [comment]
```
data {
             int<lower=0> J;
             real y[J];
             real<lower=0> sigma[J];
}
parameters {
             real mu;
             real<lower=0> tau;
             real rheta_tilde[J];
}
transformed parameters {
             real theta[J];
             for (j in 1:J)
                 theta[j] = mu + tau * rheta_tilde[j];
}
model {
             mu ~ normal(0, 5);
             tau ~ cauchy(0, 5);
             rheta_tilde ~ normal(0, 1);
             y ~ normal(theta, sigma);
}
generated quantities {
             vector[J] log_lik;
             vector[J] my_hat;
             for (j in 1:J) {
                 log_lik[j] = normal_lpdf(y[j] | theta[j], sigma[j]);
                 my_hat[j] = normal_rng(theta[j], sigma[j]);
             }
}
```

This works

**Comment by ahartikainen** [comment]
This PR will fix the problem https://github.com/stan-dev/httpstan/pull/140
